"""T012 — migrate legacy agent files' manual content into AGENTS.md.

Spec: specs/0016-agent-skills-interop/spec.md, Story 3 scenario 2 + 3.
Plan: ADR-5 follow-up — T011 made AGENTS.md the canonical agent file and
turned CLAUDE.md/GEMINI.md into thin wrappers. Projects that installed
under the *old* layout have a CLAUDE.md (or GEMINI.md) that is not a
wrapper: it carries real hand-written content (the team's own
conventions) alongside the managed ``<!-- aiadev:auto-stack -->`` block.
Flipping such a project onto the new layout must not silently discard
that manual content.

This module covers the one-time migration `aiadev sync` performs before
regenerating the stack block (see ``_migrate_legacy_agent_file`` in
``src/aiadev/commands/sync.py``):

* legacy CLAUDE.md (manual prose + managed block) -> content moved into
  AGENTS.md, ``CLAUDE.md.bak`` written with the original bytes, CLAUDE.md
  rewritten as the thin wrapper.
* idempotent: a second sync makes no further changes.
* a pre-existing hand-authored AGENTS.md is preserved — the legacy
  CLAUDE.md's manual content is appended, not used to clobber it.
* GEMINI.md parity via the same helper.
* a CLAUDE.md that is *already* the thin wrapper is left untouched (no
  ``.bak``, no rewrite) — the migration only fires for genuine legacy
  files.
"""
from __future__ import annotations

import pathlib

import pytest
from click.testing import CliRunner

from aiadev.commands.install import install_command
from aiadev.commands.sync import sync_command

_LEGACY_MANUAL_TEXT = (
    "# LegacyDemo\n\n"
    "## Team conventions\n\n"
    "- We always squash-merge.\n"
    "- Staging deploys happen on Fridays only if Alice approves.\n"
)

_LEGACY_STACK_BLOCK = (
    "<!-- aiadev:auto-stack:start -->\n"
    "## Detected stack\n\n"
    "_No recognised stack files found._\n\n"
    "_Regenerated by `aiadev sync` on 2020-01-01T00:00:00Z._\n"
    "<!-- aiadev:auto-stack:end -->\n"
)


def _install(
    project: pathlib.Path,
    *,
    platform: str,
    project_name: str = "LegacyDemo",
) -> object:
    runner = CliRunner()
    args = [
        "--project-root",
        str(project),
        "--preset",
        "lean",
        "--non-interactive",
        "--vars",
        f"PROJECT_NAME={project_name}",
        "--platform",
        platform,
    ]
    return runner.invoke(install_command, args)


def _sync(project: pathlib.Path, *, platform: str):
    runner = CliRunner()
    args = ["--project-root", str(project), "--platform", platform]
    return runner.invoke(sync_command, args)


def _mark_wrapper_as_tracked(project: pathlib.Path, agent_filename: str) -> None:
    """Point the manifest's wrapper entry at the file's current on-disk hash.

    Simulates a manifest written by a pre-T011 ``aiadev``: the wrapper
    file (CLAUDE.md/GEMINI.md) is tracked as sync-owned with the legacy
    full-content bytes, which is the migration's trigger condition (a).
    """
    from aiadev.install_manifest import (
        InstalledFile,
        compute_sha256,
        load as load_manifest,
        save as save_manifest,
    )

    manifest_path = project / ".aiadev" / "installed.yaml"
    manifest = load_manifest(manifest_path)
    preset = manifest.find_preset("lean")
    assert preset is not None
    new_sha = compute_sha256(project / agent_filename)
    preset.files = [
        InstalledFile(path=f.path, sha256=new_sha, role=f.role)
        if f.path == agent_filename
        else f
        for f in preset.files
    ]
    save_manifest(manifest, manifest_path)


def _make_legacy_project(
    tmp_path: pathlib.Path,
    isolated_framework: pathlib.Path,
    monkeypatch,
    *,
    platform: str,
    agent_filename: str,
    dirname: str,
    seed_agents_md: str | None = None,
) -> pathlib.Path:
    """Install fresh (T011 layout), then rewrite disk state to look pre-T011.

    A fresh install always produces the canonical AGENTS.md + thin
    wrapper. To exercise the migration we then overwrite the wrapper
    file with legacy content (manual prose + a managed block) as if it
    had never been flipped, optionally seed AGENTS.md with team-authored
    content, and — critically — drop both files from the manifest's
    hash tracking for the *old* wrapper shape so the scenario matches an
    upgrade from a pre-T011 ``aiadev`` where the manifest recorded the
    old (full-content) CLAUDE.md hash.
    """
    monkeypatch.setenv("AIADEV_ROOT", str(isolated_framework))
    project = tmp_path / dirname
    project.mkdir()
    result = _install(project, platform=platform)
    assert result.exit_code == 0, result.output

    agent_path = project / agent_filename
    legacy_text = _LEGACY_MANUAL_TEXT + "\n" + _LEGACY_STACK_BLOCK
    agent_path.write_text(legacy_text, encoding="utf-8")

    agents_md = project / "AGENTS.md"
    if seed_agents_md is not None:
        agents_md.write_text(seed_agents_md, encoding="utf-8")

    # Simulate a manifest that still tracks the wrapper file's *old*
    # (legacy, full-content) hash — i.e. this project installed before
    # T011 ever existed and the wrapper file is not new/foreign. This is
    # the "tracked as sync-owned" trigger condition (see
    # _migrate_legacy_agent_file's docstring in sync.py).
    from aiadev.install_manifest import (
        InstalledFile,
        compute_sha256,
        load as load_manifest,
        save as save_manifest,
    )

    manifest_path = project / ".aiadev" / "installed.yaml"
    manifest = load_manifest(manifest_path)
    preset = manifest.find_preset("lean")
    assert preset is not None
    new_sha = compute_sha256(agent_path)
    updated_files = []
    for f in preset.files:
        if f.path == agent_filename:
            updated_files.append(InstalledFile(path=f.path, sha256=new_sha, role=f.role))
        else:
            updated_files.append(f)
    preset.files = updated_files
    if seed_agents_md is not None:
        # The manifest must NOT recognize this AGENTS.md hash either —
        # it's hand-authored, never installed by aiadev. Drop tracking
        # for it entirely so it reads as "pre-existing manual content",
        # matching Story 3 scenario 2.
        preset.files = [f for f in preset.files if f.path != "AGENTS.md"]
    save_manifest(manifest, manifest_path)

    return project


class TestClaudeLegacyMigration:
    @pytest.fixture
    def legacy_project(self, isolated_framework, tmp_path, monkeypatch):
        return _make_legacy_project(
            tmp_path,
            isolated_framework,
            monkeypatch,
            platform="claude-code",
            agent_filename="CLAUDE.md",
            dirname="claude-legacy",
        )

    def test_sync_moves_manual_content_into_agents_md(self, legacy_project):
        result = _sync(legacy_project, platform="claude-code")
        assert result.exit_code == 0, result.output

        agents_text = (legacy_project / "AGENTS.md").read_text(encoding="utf-8")
        assert "Team conventions" in agents_text
        assert "squash-merge" in agents_text
        assert "<!-- aiadev:auto-stack:start -->" in agents_text

    def test_sync_writes_bak_with_original_bytes(self, legacy_project):
        original_bytes = (legacy_project / "CLAUDE.md").read_bytes()

        result = _sync(legacy_project, platform="claude-code")
        assert result.exit_code == 0, result.output

        bak_path = legacy_project / "CLAUDE.md.bak"
        assert bak_path.is_file()
        assert bak_path.read_bytes() == original_bytes

    def test_sync_rewrites_claude_md_as_wrapper(self, legacy_project):
        result = _sync(legacy_project, platform="claude-code")
        assert result.exit_code == 0, result.output

        claude_text = (legacy_project / "CLAUDE.md").read_text(encoding="utf-8")
        lines = [line for line in claude_text.splitlines() if line.strip()]
        assert len(lines) <= 5
        assert "AGENTS.md" in claude_text
        assert "Team conventions" not in claude_text
        assert "<!-- aiadev:auto-stack:start -->" not in claude_text

    def test_second_sync_is_idempotent(self, legacy_project):
        first = _sync(legacy_project, platform="claude-code")
        assert first.exit_code == 0, first.output

        agents_after_first = (legacy_project / "AGENTS.md").read_bytes()
        claude_after_first = (legacy_project / "CLAUDE.md").read_bytes()
        bak_after_first = (legacy_project / "CLAUDE.md.bak").read_bytes()

        second = _sync(legacy_project, platform="claude-code")
        assert second.exit_code == 0, second.output
        assert "conflict" not in second.output.lower()

        assert (legacy_project / "AGENTS.md").read_bytes() == agents_after_first
        assert (legacy_project / "CLAUDE.md").read_bytes() == claude_after_first
        assert (legacy_project / "CLAUDE.md.bak").read_bytes() == bak_after_first


class TestClaudePreExistingAgentsMdPreserved:
    def test_both_manual_contents_survive(self, isolated_framework, tmp_path, monkeypatch):
        team_agents_md = (
            "# LegacyDemo\n\n## Team-authored AGENTS.md\n\n"
            "- This file was hand-written before anyone ran aiadev sync.\n"
        )
        project = _make_legacy_project(
            tmp_path,
            isolated_framework,
            monkeypatch,
            platform="claude-code",
            agent_filename="CLAUDE.md",
            dirname="claude-both-manual",
            seed_agents_md=team_agents_md,
        )

        result = _sync(project, platform="claude-code")
        # AGENTS.md itself is hand-authored and was never installed by
        # aiadev (no manifest entry for it at all — see
        # _make_legacy_project's seed_agents_md handling), so the
        # ordinary, pre-existing install-engine conflict rule correctly
        # refuses to blindly overwrite it with the preset's fresh render
        # (exit code 1, "conflict" reported, --force is the escape
        # hatch). That is orthogonal to T012: this test's job is to
        # confirm neither manual text is lost in the process, which
        # step 1 leaving the file untouched on conflict guarantees.
        assert result.exit_code == 1, result.output
        assert "conflict" in result.output.lower()

        agents_text = (project / "AGENTS.md").read_text(encoding="utf-8")
        assert "Team-authored AGENTS.md" in agents_text
        assert "Team conventions" in agents_text
        assert "squash-merge" in agents_text
        assert "<!-- aiadev:auto-stack:start -->" in agents_text

        bak_path = project / "CLAUDE.md.bak"
        assert bak_path.is_file()


class TestGeminiLegacyMigration:
    @pytest.fixture
    def legacy_project(self, isolated_framework, tmp_path, monkeypatch):
        return _make_legacy_project(
            tmp_path,
            isolated_framework,
            monkeypatch,
            platform="gemini",
            agent_filename="GEMINI.md",
            dirname="gemini-legacy",
        )

    def test_sync_moves_manual_content_and_writes_bak(self, legacy_project):
        original_bytes = (legacy_project / "GEMINI.md").read_bytes()

        result = _sync(legacy_project, platform="gemini")
        assert result.exit_code == 0, result.output

        agents_text = (legacy_project / "AGENTS.md").read_text(encoding="utf-8")
        assert "Team conventions" in agents_text
        assert "squash-merge" in agents_text

        bak_path = legacy_project / "GEMINI.md.bak"
        assert bak_path.is_file()
        assert bak_path.read_bytes() == original_bytes

        gemini_text = (legacy_project / "GEMINI.md").read_text(encoding="utf-8")
        lines = [line for line in gemini_text.splitlines() if line.strip()]
        assert len(lines) <= 5
        assert "AGENTS.md" in gemini_text
        assert "Team conventions" not in gemini_text

    def test_second_sync_is_idempotent(self, legacy_project):
        first = _sync(legacy_project, platform="gemini")
        assert first.exit_code == 0, first.output

        second = _sync(legacy_project, platform="gemini")
        assert second.exit_code == 0, second.output
        assert "conflict" not in second.output.lower()


_FENCED_FAKE_AUTOSTACK_SAMPLE = (
    "```markdown\n"
    "<!-- aiadev:auto-stack:start -->\n"
    "## Detected stack\n"
    "<!-- aiadev:auto-stack:end -->\n"
    "```"
)

_FENCED_FAKE_MIGRATED_SAMPLE = (
    "```markdown\n"
    "<!-- aiadev:migrated-legacy:start -->\n"
    "example payload shown in docs\n"
    "<!-- aiadev:migrated-legacy:end -->\n"
    "```"
)


class TestFenceAwareMigration:
    """Adversarial inputs: marker syntax quoted inside fenced code samples.

    The marker strings appear verbatim in the framework's own docs, so a
    legacy CLAUDE.md whose manual prose *documents* the managed-block
    syntax inside a fenced code sample is realistic. Neither the
    migration's managed-block stripping nor the later re-extraction of
    the migrated-legacy payload may treat those fenced samples as real
    block boundaries.
    """

    def test_fenced_fake_autostack_markers_survive_migration_intact(
        self, isolated_framework, tmp_path, monkeypatch
    ):
        monkeypatch.setenv("AIADEV_ROOT", str(isolated_framework))
        project = tmp_path / "claude-fenced-autostack"
        project.mkdir()
        result = _install(project, platform="claude-code")
        assert result.exit_code == 0, result.output

        legacy_text = (
            "# LegacyDemo\n\n"
            "## How our managed block works\n\n"
            "The sync tool maintains a block that looks like this:\n\n"
            f"{_FENCED_FAKE_AUTOSTACK_SAMPLE}\n\n"
            "- Real convention: we always squash-merge.\n\n"
            + _LEGACY_STACK_BLOCK
        )
        (project / "CLAUDE.md").write_text(legacy_text, encoding="utf-8")
        _mark_wrapper_as_tracked(project, "CLAUDE.md")

        sync_result = _sync(project, platform="claude-code")
        assert sync_result.exit_code == 0, sync_result.output

        agents_text = (project / "AGENTS.md").read_text(encoding="utf-8")
        # The fenced sample — fake markers and all — survives byte-intact
        # inside the migrated-legacy block; only the REAL managed block
        # was stripped from the migrated content.
        assert _FENCED_FAKE_AUTOSTACK_SAMPLE in agents_text
        assert "How our managed block works" in agents_text
        assert "squash-merge" in agents_text
        # The legacy file's REAL (stale, 2020-stamped) auto-stack block
        # was stripped rather than migrated: only the freshly regenerated
        # block's timestamp may appear.
        assert "2020-01-01T00:00:00Z" not in agents_text

    def test_fenced_fake_migrated_legacy_markers_round_trip_byte_stable(
        self, isolated_framework, tmp_path, monkeypatch
    ):
        monkeypatch.setenv("AIADEV_ROOT", str(isolated_framework))
        project = tmp_path / "claude-fenced-migrated"
        project.mkdir()
        result = _install(project, platform="claude-code")
        assert result.exit_code == 0, result.output

        legacy_text = (
            "# LegacyDemo\n\n"
            "Pasted example of the migration block syntax:\n\n"
            f"{_FENCED_FAKE_MIGRATED_SAMPLE}\n\n"
            "Tail content after the fence that must never be truncated away.\n\n"
            + _LEGACY_STACK_BLOCK
        )
        (project / "CLAUDE.md").write_text(legacy_text, encoding="utf-8")
        _mark_wrapper_as_tracked(project, "CLAUDE.md")

        first = _sync(project, platform="claude-code")
        assert first.exit_code == 0, first.output

        agents_after_first = (project / "AGENTS.md").read_text(encoding="utf-8")
        assert _FENCED_FAKE_MIGRATED_SAMPLE in agents_after_first
        assert "Tail content after the fence" in agents_after_first

        # Second sync must re-extract the FULL payload (no truncation at
        # the fenced fake `:end` marker) and re-apply it byte-identically.
        second = _sync(project, platform="claude-code")
        assert second.exit_code == 0, second.output
        assert "conflict" not in second.output.lower()

        agents_after_second = (project / "AGENTS.md").read_text(encoding="utf-8")
        assert agents_after_second == agents_after_first
        assert _FENCED_FAKE_MIGRATED_SAMPLE in agents_after_second
        assert "Tail content after the fence" in agents_after_second


class TestAlreadyWrapperUntouched:
    def test_fresh_install_wrapper_is_not_migrated(
        self, isolated_framework, tmp_path, monkeypatch
    ):
        monkeypatch.setenv("AIADEV_ROOT", str(isolated_framework))
        project = tmp_path / "claude-fresh"
        project.mkdir()
        result = _install(project, platform="claude-code")
        assert result.exit_code == 0, result.output

        claude_before = (project / "CLAUDE.md").read_bytes()

        sync_result = _sync(project, platform="claude-code")
        assert sync_result.exit_code == 0, sync_result.output

        assert not (project / "CLAUDE.md.bak").exists()
        assert (project / "CLAUDE.md").read_bytes() == claude_before
