"""Content tests for ``skills/implement/SKILL.md``.

Spec: ``specs/0013-implement-task-status-tracking/spec.md`` (Story 3 sc1).

Originally planned as a drift-check between two tracked copies of the
implement skill, but the repo's gitignore puts both ``.claude/skills/``
and ``src/aiadev/_assets/skills/`` under ignore (the former is
per-developer, the latter is a build artefact regenerated by
``scripts/sync_assets.py``). The single tracked source-of-truth is
``skills/implement/SKILL.md``, so this file enforces the Story 3
contract there.
"""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BARE_SKILL = ROOT / "skills" / "implement" / "SKILL.md"

# Substrings the loop sub-procedure must contain. Anchored on the
# orchestrator's status-flip contract (spec Story 3 sc1).
REQUIRED_LOOP_PHRASES = (
    "**Status:** pending",
    "**Status:** done",
    "git restore --staged tasks.md",
    "git checkout -- tasks.md",
    "orchestrator",
)


def test_loop_section_contains_status_flip_subprocedure() -> None:
    """Story 3 sc1: the loop section spells out the orchestrator's
    status-flip sub-procedure verbatim — file edit, transform,
    commit timing, rollback. A reader scanning the loop section
    sees the rule, not a half-sentence handwave."""
    text = BARE_SKILL.read_text(encoding="utf-8")

    # Slice just the ``## The loop`` section so an unrelated mention
    # of these phrases elsewhere in the file does not satisfy us.
    start = text.index("## The loop")
    end = text.index("\n## ", start + 1)
    loop_section = text[start:end]

    missing = [phrase for phrase in REQUIRED_LOOP_PHRASES if phrase not in loop_section]
    assert not missing, (
        f"{BARE_SKILL.relative_to(ROOT)} loop section missing required "
        f"status-flip phrases: {missing}"
    )
