"""Detect project stack facts from well-known config files.

Called by ``aiadev sync`` to regenerate the ``<!-- aiadev:auto-stack -->``
block inside ``CLAUDE.md`` (or the per-platform agent file). The output
is deterministic: the same project files always produce the same
report, byte-for-byte, so sync runs stay idempotent.

Detection is intentionally shallow: we only read files that are cheap
to parse and widely agreed upon. AST or LSP-level introspection is
deferred; cf. spec 0007 non-goals.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

import yaml


@dataclass
class StackReport:
    """Structured facts about the project's tech stack."""

    languages: list[str] = field(default_factory=list)
    frameworks: list[str] = field(default_factory=list)
    run_commands: list[str] = field(default_factory=list)
    services: list[str] = field(default_factory=list)
    ci_pipelines: list[str] = field(default_factory=list)
    make_targets: list[str] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not any(
            (
                self.languages,
                self.frameworks,
                self.run_commands,
                self.services,
                self.ci_pipelines,
                self.make_targets,
            )
        )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def introspect(project_root: Path) -> StackReport:
    """Scan ``project_root`` and return a :class:`StackReport`.

    Safe to call on an empty or unknown directory — returns a report
    whose ``is_empty`` is True.
    """
    report = StackReport()
    _detect_node(project_root, report)
    _detect_python(project_root, report)
    _detect_rust(project_root, report)
    _detect_go(project_root, report)
    _detect_dart(project_root, report)
    _detect_docker(project_root, report)
    _detect_make(project_root, report)
    _detect_task(project_root, report)
    _detect_github_actions(project_root, report)

    # Stable order: alphabetised so re-running sync does not cause
    # spurious diffs just because a set iteration order changed.
    report.languages = sorted(set(report.languages))
    report.frameworks = sorted(set(report.frameworks))
    report.run_commands = sorted(set(report.run_commands))
    report.services = sorted(set(report.services))
    report.ci_pipelines = sorted(set(report.ci_pipelines))
    report.make_targets = sorted(set(report.make_targets))
    return report


def render_stack_block(report: StackReport, generated_at: str) -> str:
    """Produce the markdown block that goes between the auto-stack markers.

    ``generated_at`` is an ISO-8601 UTC timestamp supplied by the caller
    so tests can pin it.
    """
    lines: list[str] = ["## Detected stack", ""]
    if report.is_empty:
        lines.append("_No recognised stack files found._")
        lines.append("")
    else:
        if report.languages:
            lines.append(f"- **Languages:** {', '.join(report.languages)}")
        if report.frameworks:
            lines.append(f"- **Frameworks:** {', '.join(report.frameworks)}")
        if report.run_commands:
            lines.append(f"- **Run:** {', '.join(f'`{c}`' for c in report.run_commands)}")
        if report.make_targets:
            lines.append(
                f"- **Make targets:** {', '.join(f'`{t}`' for t in report.make_targets)}"
            )
        if report.services:
            lines.append(f"- **Services:** {', '.join(report.services)}")
        if report.ci_pipelines:
            lines.append(f"- **CI:** {', '.join(report.ci_pipelines)}")
        lines.append("")
    lines.append(f"_Regenerated by `aiadev sync` on {generated_at}._")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-tech detectors (kept tiny and boring)
# ---------------------------------------------------------------------------


def _read_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _read_yaml(path: Path) -> dict | None:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return None
    return data if isinstance(data, dict) else None


def _detect_node(root: Path, report: StackReport) -> None:
    pkg_json = root / "package.json"
    if not pkg_json.is_file():
        return
    data = _read_json(pkg_json) or {}
    report.languages.append("JavaScript/TypeScript")
    scripts = data.get("scripts") or {}
    for key in ("dev", "start", "build", "test", "lint"):
        if key in scripts:
            report.run_commands.append(f"npm run {key}")
    deps = {**(data.get("dependencies") or {}), **(data.get("devDependencies") or {})}
    for label, markers in (
        ("React", ("react",)),
        ("Next.js", ("next",)),
        ("Vue", ("vue",)),
        ("Nuxt", ("nuxt",)),
        ("Expo", ("expo",)),
        ("Vite", ("vite",)),
        ("Angular", ("@angular/core",)),
        ("Svelte", ("svelte",)),
    ):
        if any(m in deps for m in markers):
            report.frameworks.append(label)
    if (root / "tsconfig.json").is_file():
        report.languages.append("TypeScript")


def _detect_python(root: Path, report: StackReport) -> None:
    pyproject = root / "pyproject.toml"
    requirements = root / "requirements.txt"
    if not pyproject.is_file() and not requirements.is_file():
        return
    report.languages.append("Python")

    blob = ""
    if pyproject.is_file():
        blob += pyproject.read_text(encoding="utf-8")
    if requirements.is_file():
        blob += "\n" + requirements.read_text(encoding="utf-8")
    lower = blob.lower()

    for label, needle in (
        ("Django", "django"),
        ("FastAPI", "fastapi"),
        ("Flask", "flask"),
        ("Celery", "celery"),
        ("DRF", "djangorestframework"),
        ("Pydantic", "pydantic"),
    ):
        if needle in lower:
            report.frameworks.append(label)

    manage_py = root / "manage.py"
    if manage_py.is_file():
        report.run_commands.append("python manage.py runserver")
        report.run_commands.append("python manage.py test")


def _detect_rust(root: Path, report: StackReport) -> None:
    if (root / "Cargo.toml").is_file():
        report.languages.append("Rust")
        report.run_commands.append("cargo build")
        report.run_commands.append("cargo test")


def _detect_go(root: Path, report: StackReport) -> None:
    if (root / "go.mod").is_file():
        report.languages.append("Go")
        report.run_commands.append("go test ./...")


def _detect_dart(root: Path, report: StackReport) -> None:
    pubspec = root / "pubspec.yaml"
    if pubspec.is_file():
        report.languages.append("Dart")
        data = _read_yaml(pubspec) or {}
        if "flutter" in (data.get("dependencies") or {}):
            report.frameworks.append("Flutter")


def _detect_docker(root: Path, report: StackReport) -> None:
    compose = None
    for candidate in ("docker-compose.yml", "docker-compose.yaml", "compose.yml"):
        path = root / candidate
        if path.is_file():
            compose = path
            break
    if compose is None:
        return
    data = _read_yaml(compose) or {}
    services = data.get("services") or {}
    if isinstance(services, dict):
        report.services.extend(services.keys())


def _detect_make(root: Path, report: StackReport) -> None:
    makefile = root / "Makefile"
    if not makefile.is_file():
        return
    target_re = re.compile(r"^([a-zA-Z][a-zA-Z0-9_.-]*)\s*:")
    for line in makefile.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("."):
            continue
        match = target_re.match(line)
        if match and not line.startswith("\t"):
            name = match.group(1)
            if name in {"PHONY", "DEFAULT_GOAL", "SUFFIXES"}:
                continue
            report.make_targets.append(name)


def _detect_task(root: Path, report: StackReport) -> None:
    taskfile = root / "Taskfile.yml"
    if not taskfile.is_file():
        return
    data = _read_yaml(taskfile) or {}
    tasks = data.get("tasks") or {}
    if isinstance(tasks, dict):
        for key in tasks.keys():
            report.make_targets.append(f"task:{key}")


def _detect_github_actions(root: Path, report: StackReport) -> None:
    workflows_dir = root / ".github" / "workflows"
    if not workflows_dir.is_dir():
        return
    for path in sorted(workflows_dir.iterdir()):
        if path.suffix in (".yml", ".yaml") and path.is_file():
            report.ci_pipelines.append(path.name)


# ---------------------------------------------------------------------------
# CLAUDE.md marker handling
# ---------------------------------------------------------------------------

_MARKER_START = "<!-- aiadev:auto-stack:start -->"
_MARKER_END = "<!-- aiadev:auto-stack:end -->"
_MARKER_RE = re.compile(
    r"(<!-- aiadev:auto-stack:start -->)(.*?)(<!-- aiadev:auto-stack:end -->)",
    re.DOTALL,
)


def apply_stack_block(text: str, block: str) -> tuple[str, bool]:
    """Replace the content between the auto-stack markers with ``block``.

    Returns ``(new_text, appended)``:

    * ``appended`` is True when the markers were missing and the block
      was appended at the end of the file (with a blank line buffer).
      Callers may surface a warning to the user.
    * ``appended`` is False when the markers existed and the block
      replaced the previous content in place. Everything outside the
      markers is preserved byte-for-byte.
    """
    replacement = f"{_MARKER_START}\n{block}\n{_MARKER_END}"
    new_text, n = _MARKER_RE.subn(lambda _m: replacement, text, count=1)
    if n == 0:
        sep = "" if text.endswith("\n") else "\n"
        appended = f"{text}{sep}\n{replacement}\n"
        return appended, True
    return new_text, False


def stack_markers() -> Iterable[str]:
    """Expose the marker strings for callers that need to inject them."""
    return (_MARKER_START, _MARKER_END)
