#!/usr/bin/env python3
"""Emit docs/pipeline-reference.md from skill frontmatter (spec 0009 T008).

Walks ``skills/`` + ``presets/*/skills/`` at the repo root, reads each
``SKILL.md``'s YAML frontmatter (``name``, ``description``, ``handoffs``),
and renders the pipeline commands as a terse Markdown table. Skills that
are not part of the pipeline (``frontend-design``, ``using-ai-augmented-developer``,
``systematic-debugging``, ``constitution``, ``test-driven-development``,
``sync``, anything not reachable from ``specify``) are filtered out so the
output stays within the 24-line / 600-token budget.

Deterministic: skills are ordered by the canonical pipeline sequence, not
by filesystem walk order.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import yaml

ROOT = Path(__file__).resolve().parents[1]

# Canonical pipeline order — authoritative list for the Quick Reference.
# Mirrors the table in root CLAUDE.md "What you're doing | Skill to invoke".
PIPELINE: tuple[str, ...] = (
    "specify",
    "clarify",
    "plan",
    "tasks",
    "implement",
    "analyze",
    "checklist",
    "requesting-code-review",
    "finishing-a-branch",
    "help",
)


def _read_frontmatter(skill_md: Path) -> dict | None:
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    _, _, rest = text.partition("---\n")
    payload, _, _ = rest.partition("\n---")
    try:
        return yaml.safe_load(payload) or {}
    except yaml.YAMLError:
        return None


def _discover_skills(repo_root: Path) -> dict[str, dict]:
    found: dict[str, dict] = {}
    for skill_md in sorted(repo_root.glob("skills/*/SKILL.md")):
        fm = _read_frontmatter(skill_md)
        if fm and fm.get("name"):
            found[fm["name"]] = fm
    for skill_md in sorted(repo_root.glob("presets/*/skills/*/SKILL.md")):
        fm = _read_frontmatter(skill_md)
        if fm and fm.get("name"):
            found.setdefault(fm["name"], fm)
    return found


def _format_handoffs(handoffs: Iterable[str] | None) -> str:
    if not handoffs:
        return "—"
    items = [h for h in handoffs if h in PIPELINE]
    if not items:
        return "—"
    return " | ".join(items)


def _compose_one_liner(description: str) -> str:
    """Keep each description to a single terse sentence under 90 chars."""
    first = description.strip().splitlines()[0]
    # First ". " (period + whitespace) marks the sentence boundary —
    # splitting on bare "." would chop filenames like "spec.md".
    if ". " in first:
        first = first.split(". ", 1)[0] + "."
    if len(first) > 90:
        first = first[:87].rstrip() + "…"
    return first


def render(repo_root: Path) -> str:
    skills = _discover_skills(repo_root)

    lines = [
        "# Pipeline quick reference",
        "",
        "<!-- generated by scripts/generate_pipeline_reference.py — do not edit by hand -->",
        "",
        "| Command | What it does | Next |",
        "|---|---|---|",
    ]
    for name in PIPELINE:
        fm = skills.get(name)
        if fm is None:
            # Skill not yet landed; render a placeholder so drift is visible.
            lines.append(f"| `/aiadev:{name}` | _missing_ | — |")
            continue
        description = _compose_one_liner(fm.get("description", ""))
        nxt = _format_handoffs(fm.get("handoffs"))
        lines.append(f"| `/aiadev:{name}` | {description} | → {nxt} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "pipeline-reference.md",
        help="Destination file (default: docs/pipeline-reference.md).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help="Repository root (default: auto-detected from script location).",
    )
    args = parser.parse_args()

    body = render(args.root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
